---
stages:
  - build
  - release

build_job:
  stage: build
  image: php:8.1
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apt-get update -y
    - apt-get install -y git unzip libgmp3-dev
    - docker-php-ext-install pdo_mysql gmp
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install --no-dev --optimize-autoloader
    - mkdir moon-mining-manager
    - mv app moon-mining-manager/app
    - mv bootstrap moon-mining-manager/bootstrap
    - mv config moon-mining-manager/config
    - mv database moon-mining-manager/database
    - mv public moon-mining-manager/public
    - mv resources moon-mining-manager/resources
    - mv routes moon-mining-manager/routes
    - mv storage moon-mining-manager/storage
    - mv vendor moon-mining-manager/vendor
    - mv .env.example moon-mining-manager/.env.example
    - mv LICENSE moon-mining-manager/LICENSE
    - mv README.md moon-mining-manager/README.md
    - mv artisan moon-mining-manager/artisan
    - mv package-lock.json moon-mining-manager/package-lock.json
    - echo "BUILD_JOB_ID=$CI_JOB_ID" > build.env
    - tar czf moon-mining-manager-$CI_COMMIT_TAG.tar.gz moon-mining-manager/
  artifacts:
    name: 'moon-mining-manager-$CI_COMMIT_TAG'
    paths:
      - 'moon-mining-manager-$CI_COMMIT_TAG.tar.gz'
    expire_in: never
    reports:
      dotenv: build.env

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build_job
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Create release."
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'moon-mining-manager-$CI_COMMIT_TAG.zip'
          url: '$CI_SERVER_URL/$CI_PROJECT_PATH/-/jobs/$BUILD_JOB_ID/artifacts/download'

