version: '3'

services:
  moon_php:
    container_name: moon_dev_php
    build:
      context: config
      dockerfile: dockerfile-php
    volumes: [ ".:/app" ]
    working_dir: /app

  moon_node:
    container_name: moon_dev_node
    image: node:16-alpine
    volumes: [ ".:/app" ]
    working_dir: /app

  moon_http:
    container_name: moon_dev_http
    image: nginx:1
    depends_on: [ moon_php ]
    volumes: [ ".:/app", "./config/docker-nginx.conf:/etc/nginx/conf.d/default.conf" ]
    ports: [ "8000:80" ]
