<?php

return [
    'DB_CONNECTION' => env('DB_CONNECTION'),
    'DB_HOST' => env('DB_HOST'),
    'DB_PORT' => env('DB_PORT'),
    'DB_DATABASE' => env('DB_DATABASE'),
    'DB_USERNAME' => env('DB_USERNAME'),
    'DB_PASSWORD' => env('DB_PASSWORD'),
    'EVEONLINE_CLIENT_ID' => env('EVEONLINE_CLIENT_ID'),
    'EVEONLINE_CLIENT_SECRET' => env('EVEONLINE_CLIENT_SECRET'),
    'EVEONLINE_REDIRECT' => env('EVEONLINE_REDIRECT'),
    'TAX_CORPORATION_ID' => env('TAX_CORPORATION_ID'),
    'TAX_CORPORATION_PRIME_USER_ID' => env('TAX_CORPORATION_PRIME_USER_ID'),
];
