---
name: Build Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Validate composer json/lock
        run: composer validate --strict

      - name: Composer install
        run: composer install --no-dev --optimize-autoloader

#     - run: npm ci

#     - name: Build js
#       run: npm run build

#     - name: Compress artifacts
#       run: >
#         tar czf moon-mining-manager-$CI_COMMIT_TAG.tar.gz
#         app/
#         bootstrap/
#         config/
#         database/
#         public/
#         resources/
#         routes/
#         storage/
#         vendor/
#         .env.example
#         LICENSE
#         README.md
#         artisan
#         composer.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        id: artifact
        with:
          path: |
            app/
            bootstrap/
            config/
            database/
            public/
            resources/
            routes/
            storage/
            vendor/
            .env.example
            LICENSE
            README.md
            artisan
            composer.json

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ steps.artifact.outputs.artifact-id }}
